import { Product } from "./types";

export const products: Product[] = [
    {
        id: 'prod001',
        title: 'Blue Denim Jacket',
        description: 'Classic blue denim jacket with button closure',
        link: 'https://example.com/products/blue-denim-jacket',
        image_link: 'https://example.com/images/blue-denim-jacket.jpg',
        price: '49.99 USD',
        availability: 'in stock',
        brand: 'Fashion Brand',
        condition: 'new',
        gtin: '9876543210987',
        mpn: 'DENIM-BJ-001',
        gender: 'unisex',
        age_group: 'adult',
        color: 'blue',
        size: 'M',
        material: 'denim',
      },
      {
        id: 'prod002',
        title: 'Red Cotton T-Shirt',
        description: 'Comfortable red cotton t-shirt',
        link: 'https://example.com/products/red-cotton-tshirt',
        image_link: 'https://example.com/images/red-cotton-tshirt.jpg',
        price: '19.99 USD',
        availability: 'in stock',
        brand: 'Fashion Brand',
        condition: 'new',
        gtin: '9876543210988',
        mpn: 'COTTON-TS-R-001',
        gender: 'unisex',
        age_group: 'adult',
        color: 'red',
        // Missing size and material 
    },
    {
        id: 'prod003',
        title: 'Blue Denim Pants',
        description: 'Classic blue denim jacket with button closure',
        link: 'https://example.com/products/blue-denim-jacket',
        image_link: 'https://example.com/images/blue-denim-jacket.jpg',
        price: '49.99 USD',
        availability: 'in stock',
        brand: 'Fashion Brand',
        condition: 'new',
        gtin: '9876543210987',
        mpn: 'DENIM-BJ-001',
        gender: 'unisex',
        age_group: 'adult',
        color: 'blue',
        size: 'M',
        material: 'denim',
    },
    {
        id: 'prod004',
        title: 'Cargo Pants',
        description: 'Classic blue denim jacket with button closure',
        link: 'https://example.com/products/blue-denim-jacket',
        image_link: 'https://example.com/images/blue-denim-jacket.jpg',
        price: '49.99 USD',
        availability: 'in stock',
        brand: 'Fashion Brand',
        condition: 'new',
        gtin: '9876543210987',
        mpn: 'DENIM-BJ-001',
        gender: 'unisex',
        age_group: 'adult',
        color: 'blue',
        size: 'M',
        material: 'denim',
    },
    {
        id: 'prod005',
        title: 'Red Joggers',
        description: 'Comfortable red cotton t-shirt',
        link: 'https://example.com/products/red-cotton-tshirt',
        image_link: 'https://example.com/images/red-cotton-tshirt.jpg',
        price: '19.99 USD',
        availability: 'in stock',
        brand: 'Fashion Brand',
        condition: 'new',
        gtin: '9876543210988',
        mpn: 'COTTON-TS-R-001',
        gender: 'unisex',
        age_group: 'adult',
        color: 'red',
        // Missing size and material 
    },
]

// ASSUMING THESE ARE THE REQUIRED FIELDS ON THE GOOGLE MERCHANT CENTER
export const REQUIRED_FIELDS: string[] = [
    'id', 'title', 'description', 'link', 'image_link', 
    'price', 'availability', 'brand', 'condition','size','material'
  ];